apiVersion: batch/v1
kind: Job
metadata:
  name: conf-num-replicas
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
        - name: cockroachdb-client
          image: cockroachdb/cockroach:v20.1.1
          imagePullPolicy: Always
          command: ["cockroach"]
          args:
            [
              "sql",
              "--insecure",
              "--host=cockroachdb-public",
              "--execute=ALTER RANGE default CONFIGURE ZONE USING num_replicas=5;",
            ]
      restartPolicy: Never
  backoffLimit: 1